version: "3.5"
services:
  db:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: ["mix", "phx.server"]
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - .:/app
volumes:
  pgdata: